### ISSUE TITLE
Papertrail logs not logging

### ISSUE THREAD

**Issue by ProxiBlue** [firegento/firegento-logger#116]
2018/05/23 06:56:14 [error] 167#167: *66 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Timestamp must be a number. in /vagrant/sites/enjo/docroot/lib/rsyslog/syslogmessage.php:158
Stack trace:
#0 /vagrant/sites/enjo/docroot/lib/rsyslog/syslogmessage.php(176): SyslogMessage->SetTimestamp(false)
#1 /vagrant/sites/enjo/docroot/app/code/community/FireGento/Logger/Model/Papertrailsyslog.php(121): SyslogMessage->__construct('[] [default][Ht...', 16, 'error', false, Array)
#2 /vagrant/sites/enjo/docroot/app/code/community/FireGento/Logger/Model/Rsyslog.php(181): FireGento_Logger_Model_Papertrailsyslog->buildSysLogMessage(Object(FireGento_Logger_Model_Event))
#3 /vagrant/sites/enjo/docroot/lib/Zend/Log/Writer/Abstract.php(88): FireGento_Logger_Model_Rsyslog->_write(Object(FireGento_Logger_Model_Event))
#4 /vagrant/sites/enjo/docroot/app/code/community/FireGento/Logger/Model/Queue.php(125): Zend_Log_Writer_Abstract->write(Object(FireGento_Logger_Model_Event))
#5 /vagrant/sites/enjo/docroot/lib/Zend/Log.php(366): FireGento_Logger_Model_Queue->shutdow" while reading upstream, client: 172.17.0.1, server: enjo.test, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "www.enjo.test", referrer: "https://www.enjo.test/bathroom-care.html?p=all"

**Comment by ProxiBlue** [comment]
Further testing with logly, shows the same issue there, so the problem is not just with Papertrail.

I thus need to identify why timestamp is not appearing lower level, not inside logger.
