### ISSUE TITLE
stderr: PHP Fatal error:  Class 'Zend_Log' not found in app/code/core/Mage/Core/functions.php on line 247

### ISSUE THREAD

**Issue by razbakov** [firegento/firegento-logger#75]
Accessing `/logger/error/send/` raising 500 Error.

Backtrace:

```
Warning: include(ZEND/LOG.php): failed to open stream: No such file or directory  in /var/www/share/staging.project.com/htdocs/lib/Varien/Autoload.php on line 94

#0 /var/www/share/staging.project.com/htdocs/lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(ZEND/LO...', '/var/www/share/...', 94, Array)
#1 /var/www/share/staging.project.com/htdocs/lib/Varien/Autoload.php(94): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('ZEND_LOG')
#3 /var/www/share/staging.project.com/htdocs/app/code/community/FireGento/Logger/controllers/ErrorController.php(38): spl_autoload_call('ZEND_LOG')
#4 /var/www/share/staging.project.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): FireGento_Logger_ErrorController->sendAction()
#5 /var/www/share/staging.project.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('send')
#6 /var/www/share/staging.project.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/share/staging.project.com/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/share/staging.project.com/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/share/staging.project.com/htdocs/index.php(84): Mage::run('', 'store')
#10 {main}
```

**Comment by datenbrille** [comment]
Hi, it looks like a file case problem. It tries to include ZEND/LOG.php. I guess you work on a case sensitive file system and therefore it can not locate the file. Am I wrong?

**Comment by razbakov** [comment]
Yes, I am running it on Linux.

I tried to replace `ZEND_LOG::ERR` with constant here: https://github.com/firegento/firegento-logger/blob/master/src/app/code/community/FireGento/Logger/controllers/ErrorController.php#L38
it didn't help. 

Probably file case is not the problem as core `Mage::log` raises the warning.

**Comment by datenbrille** [comment]
The constant has the wrong case. I need to check that.

**Comment by razbakov** [comment]
It is not about the constant case :(

**Comment by jlestel** [comment]
did you find the bug ?

**Comment by razbakov** [comment]
nope. can you reproduce it?

**Comment by jlestel** [comment]
yes.

i changed the case from ZEND_LOG to Zend_Log in FireGento_Logger_ErrorController
